# For all other branches, the below block will be respected.
main:
  hostname: tr.rt.gw
  user: root
  site_url: https://shalin-shah.tr.rt.gw
  main_site: shalin-shah.tr.rt.gw
  deploy_path: /opt/easyengine/sites/shalin-shah.tr.rt.gw/app/htdocs

multi_branch_env:
  hostname: tr.rt.gw
  user: root
  site_url: https://shalin-shah.tr.rt.gw
  main_site: shalin-shah.tr.rt.gw
  deploy_path: /opt/easyengine/sites/shalin-shah.tr.rt.gw/app/htdocs